DROP TABLE IF EXISTS TMP_USER;
 
CREATE TABLE TMP_USER (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  ssn VARCHAR(250) NOT NULL,
  dob VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  address VARCHAR(250) NOT NULL,
  salary integer NOT NULL,
  gender VARCHAR(250) DEFAULT NULL
);